name: Availability Scraper Cron

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Availability Scrape
        run: |
          curl -X GET "https://sjobadet.marcusjenshaug.no/api/cron/scrape-availability" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
